### ISSUE TITLE
404 error when generating REST queries

### ISSUE THREAD

**Issue by CharlieDLee** [SharePoint/PnP-JS-Core#411]
#### Category
[ ] Enhancement

[ X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.0.3 ]

#### Expected / Desired Behavior 
REST queries generated using using pnp.sp.web.lists.getByTitle('XXX').items.get() should issue the correct call to the REST endpoint and not generate a 404 error.

#### Observed Behavior
Queries issued using the above code generate a 404 error as the list name (in my case SitePages) of the hosting pages library is appended to the query,

#### Steps to Reproduce
As above.

Thanks!

**Comment by koltyakov** [comment]
Hi Charlie,

Seems like you are trying a wrong Title for the library.
`.getByTitle` operates with display names. For SitePages display name is not the `SitePages`, but `Site Pages` (in the case of 1033, it depends on locale).

Please try:

```javascript
pnp.sp.web.lists
  .getByTitle('Site Pages').items.get()
  .then(console.log)
  .catch(console.log);
```

I always recommend not to use any methods dealing with display names.
For the lists, there is an alternative:

```javascript
pnp.sp.web
  .getList(`${_spPageContextInfo.webServerRelativeUrl}/SitePages`).items.get()
  .then(console.log)
  .catch(console.log);
```

Hope, that helps with your issue. Which is not the bug at all.

--
Andrew

**Comment by patrick-rodgers** [comment]
Are you in SPFx, modern sites, etc? If the _spPageContextInfo variable is unavailable you will need to [specify the base url](https://github.com/SharePoint/PnP-JS-Core/wiki/Using-sp-pnp-js-in-SharePoint-Framework#establish-context). Also check out what @koltyakov says as well.

**Comment by CharlieDLee** [comment]
I'm just doing some more investigation on this as the results seem inconsistent.  I'll post back here with an update.

**Comment by CharlieDLee** [comment]
This has just started working again.  I have not pushed any changes to my dev tenancy, but the currently deployed components have now just started working again.  This must have just been an issue with my dev tenancy - but clearly I am slightly concerned about the likelihood of such an issue creeping into our production tenancies.

Appreciate the advice above though regarding Display Name vs Internal Name for GetByTitle and I will consider this further in the architecture of my components.

**Comment by patrick-rodgers** [comment]
Ok, sounds good @CharlieDLee - I will close this issue. Thanks for letting us know there might have been a regression - certainly don't want to break folks.

**Comment by VelinGeorgiev** [comment]
Just FYI: When I call 

`pnp.sp.web.lists.getByTitle('listtitle').get()
        .then((response) => {
              let t = response;
        })`

from react js webpart, the generated HTTP request is

`https://<site>.sharepoint.com/sites/<root>/SitePages/_api/web/lists/getByTitle('listtitle')`

I do not know if this is expected behavior, but you can see that "/SitePages/" in the url prevents the query from correct execution.

I will further investigate when have some spare time.

**Comment by CharlieDLee** [comment]
@patrick-rodgers  should this be re-opened?

**Comment by patrick-rodgers** [comment]
@VelinGeorgiev - please see [this article from the wiki](https://github.com/SharePoint/PnP-JS-Core/wiki/Using-sp-pnp-js-in-SharePoint-Framework), you need to supply the context when working within SPFx

**Comment by VelinGeorgiev** [comment]
Thanks a lot @patrick-rodgers! How I have missed that wiki article! :)

I tried to follow the wiki.
I am not sure if I am still doing it right, but these are my findings so far:
`export default class ReactYammerApiWebPart extends BaseClientSideWebPart<IReactYammerApiWebPartProps> {

  public onInit(): Promise<void> {
    return super.onInit().then(_ => {
      pnp.setup({
        spfxContext: this.context
      });
    });
  }

  public render(): void {
    
    // tests with pnp.setup
    pnp.sp.web.lists.getByTitle('YammerDatabase').select("Title").getAs<{ Title: string }>().then(w => {
      console.dir(`List Title: ${w.Title}`);  // https://mysite.sharepoint.com/sites/myrootsite/SitePages/_api/web/lists/getByTitle('YammerDatabase')?$select=Title
    }); 

    pnp.sp.web.getList('/sites/myrootsite/Lists/YammerDatabase').select("Title").getAs<{ Title: string }>().then(w => {
      console.dir(`List Title: ${w.Title}`);  // https://mysite.sharepoint.com/sites/myrootsite/SitePages/_api/web/getList('/sites/myrootsite/Lists/YammerDatabase')?$select=Title
    });

    pnp.sp.web.lists.getByTitle('YammerDatabase').get().then(r => {
      console.dir(r);  // https://mysite.sharepoint.com/sites/myrootsite/SitePages/_api/web/lists/getByTitle('YammerDatabase')
    });

    pnp.sp.web.getList('/sites/myrootsite/Lists/YammerDatabase').get().then(r => {
      console.dir(r);  // https://mysite.sharepoint.com/sites/myrootsite/SitePages/_api/web/getList('/sites/myrootsite/Lists/YammerDatabase')
    }); 

    // explicitly defined web
    let web: Web = new Web(this.context.pageContext.web.absoluteUrl);

    web.lists.getByTitle('YammerDatabase').select("Title").getAs<{ Title: string }>().then(w => {
      console.dir(`List Title: ${w.Title}`);  // https://mysite.sharepoint.com/sites/myrootsite/_api/web/lists/getByTitle('YammerDatabase')?$select=Title
    });

    web.getList('/sites/myrootsite/Lists/YammerDatabase').select("Title").getAs<{ Title: string }>().then(w => {
      console.dir(`List Title: ${w.Title}`);  // https://mysite.sharepoint.com/sites/myrootsite/_api/web/getList('/sites/myrootsite/Lists/YammerDatabase')?$select=Title
    });

    web.lists.getByTitle('YammerDatabase').get().then(r => {
      console.dir(r);  // https://mysite.sharepoint.com/sites/myrootsite/_api/web/lists/getByTitle('YammerDatabase')
    });

    web.getList('/sites/myrootsite/Lists/YammerDatabase').get().then(r => {
      console.dir(r);  // https://mysite.sharepoint.com/sites/myrootsite/_api/web/getList('/sites/myrootsite/Lists/YammerDatabase')
    });

....`

As you can see from my code comments, if I explicitly define web then it works ok. I cannot make it work with the `pnp.setup({
        spfxContext: this.context
      });` scenario. I tryied even to define the setup in the render method just before calling the list, but I could not make it work. I am using Chrome, not tested on other browsers. Will investigate further. Will let you know if more findings.

**Comment by patrick-rodgers** [comment]
I am going to reopen this for visibility as I don't notice when closed issues have comments. I am not currently able to reproduce this locally so await your findings.

**Comment by VelinGeorgiev** [comment]
Hey @patrick-rodgers,

I have submitted a pull request with fix in the "dev" branch - https://github.com/SharePoint/PnP-JS-Core/pull/419

Upper letters "FX" in config.hasOwnProperty("spFXContext ") check in file src/configuration/pnplibconfig.ts were the reason the pnp.setup not to pick the custom spfxContext for spfx webpart.

**Comment by patrick-rodgers** [comment]
Thanks @VelinGeorgiev - just merged it. Great work! Going to close this as fixed. I'll try and cut a beta later today so folks can test.

**Comment by patrick-rodgers** [comment]
This is now in sp-pnp-js@2.0.4-beta.5

**Comment by patrick-rodgers** [comment]
FYI for this thread, I just pushed 2.0.4 this morning. This was a blocking bug for folks - which isn't nice. Sorry we missed it in testing but please update to 2.0.4 and things should be back to working. Will also have a few other small fixes as well.

**Comment by CharlieDLee** [comment]
Been away for a few days but glad to see this got sorted. Team work makes the dream work!

**Comment by awildash** [comment]
Are you guys certain this is resolved? I'm running this call quite early on in the page lifecycle (before document ready):

pnp.sp.profiles.myProperties.get().then( 

On a page with a URL of:

https://<tenant>/sites/<site>/Page.aspx

And getting ta 404 as the resulting URL the call tries to use is https://<tenant>/sites/<site>/Pages/_api/sp.userprofiles.peoplemanager/getmyproperties

The chain of replies helped though, I've now added:

` pnp.setup({
                        sp: {
                            baseUrl: Helpers.getHostUrl()
                        }
                    });     `

And now the call works. I'm on a classic site (publishing site collection). Or is it just the case that you have to set a base URL?

I've noticed if the call is made after document ready its fine, URL is https://<tenant>/sites/<site>/_api/sp.userprofiles.peoplemanager/getmyproperties.

**Comment by VelinGeorgiev** [comment]
Check the sp-pnp-js version you are using.
This issue was fixed from sp-pnp-js version 2.0.4. 

If you are using the pnp js with SharePoint Framework you might have a look at this resource because there is additional setup to be made: https://github.com/SharePoint/PnP-JS-Core/wiki/Using-sp-pnp-js-in-SharePoint-Framework

**Comment by awildash** [comment]
Thanks for the quick response.

I should have said I did think of this, at the time I was running 2.0.7 so I upgraded anyway to 3.0.1 but it still happens.

No as I said I'm on a classic publishing site collection, not using SP Framework (although intention is I will be running this code in both so I'll look into that when I come to modern sites).

Have you tried calling the pnp functions before document ready? As this is when the issue occurs for me (it doesnt occur after document ready).

**Comment by koltyakov** [comment]
Hi @awildash, 

I guess you've answered your questions yourself.
PnP JS Core checks base urls in the following order:
1\. RuntimeConfig.spBaseUrl
2\. global._spPageContextInfo
2.1  _spPageContextInfo.webAbsoluteUrl
2.2 - _spPageContextInfo.webServerRelativeUrl
3\. Finally tries extract web path from window.location (will work for paths with /_layouts/, /siteassets/)

Let's assume you're are on a SharePoint page.
1.1 spBaseUrl was not provided, ok, then _spPageContextInfo comes into play
1.2 spBaseUrl was provided incorrectly, well, great power great responsibility
2. _spPageContextInfo route
2.1 _spPageContextInfo object is created in `core.js`, so, until it's loaded there is no _spPageContextInfo
3\. /_layouts/, /siteassets/ won't help with /sitepages/ or /pages/

I would recommend trying to wait for `core.js`.

**Comment by awildash** [comment]
Thanks for the response koltyakov, I thought this may the case. But does it not seem odd it defaults to /Pages in this scenario? Easy enough for JS to get the hostname (i.e. tenant root) and run the query from there instead. Especially for something like get user profile which isnt dependant on any context web URL address. Seems like a bug to me.

**Comment by koltyakov** [comment]
In most cases, I, personally, used to request current web context in the client side apps or webs in a predictable hierarchy.

For example, `${window.location.protocol}//${window.location.hostname}` will be incorrect very often. From the logical side of view (asking a wrong context) and sometimes even won't work at all.

Also, we always have an option to provide our own rule based on url parts with:

```javascript
pnp.setup({
  sp: {
    baseUrl: logicWhichGetsWebAbsolutePath()
  }
});
```

Maybe it's reasonable to extend default url parts [here](https://github.com/SharePoint/PnP-JS-Core/blob/06f8ffa9e16005854276e64bcbc39c38f3c1f159/src/utils/util.ts#L273) with /pages/, /sitepages/, etc.

To tell you the truth, I have been using PnP JS Core all over the projects for more than a year and have never faced the situation when a context path would had been resolved incorrectly. Maybe I stick with some use cases which always work. =)

**Comment by awildash** [comment]
Yes true, the baseUrl is pretty handy so this doesn't cause me any blocking issues. Ah thats where it's doing it, I was having a look for that function when debugging to see why I was ending up at /Pages. Makes sense.

Thanks for your responses.

**Comment by bva999** [comment]
I had the same problem on http://.../sites/pages/page.aspx . 
pnp.setup({
  sp: {
    baseUrl: 
  }
});
Resolved it.

**Comment by gmajsterek** [comment]
I am using sp-pnp-js version 3.0.1 and the issue is the same (404) when webpart is running on subpage.
Adding baseUrl option resolved this.
