### ISSUE TITLE
Unexpected error when deleting list item - Angular 2

### ISSUE THREAD

**Issue by garrytrinder** [SharePoint/PnP-JS-Core#487]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[ X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [     2.0.6    ]

#### Expected / Desired Behavior / Question
Using an Angular 2 application, when deleting an item, it should complete with no issue.

#### Observed Behavior
Item is being deleted, but an error is being thrown.

```
ERROR Error: Uncaught (in promise): SyntaxError: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at resolvePromise (zone.js:769)
    at resolvePromise (zone.js:740)
    at zone.js:817
    at ZoneDelegate.invokeTask (zone.js:424)
    at Object.onInvokeTask (core.es5.js:4140)
    at ZoneDelegate.invokeTask (zone.js:423)
    at Zone.runTask (zone.js:191)
    at drainMicroTaskQueue (zone.js:584)
    at <anonymous>
```

#### Steps to Reproduce
Create an Angular 2 application, delete an item using the below sample code

```
 new Web(this.webUrl).lists
            .getByTitle(this.listTitle).items
            .getById(id)
            .delete()
```

Thanks!

**Comment by patrick-rodgers** [comment]
This doesn't repro for the library running against SharePoint Online. Can you share other details that might be contributing to the error? Repro steps like "create an angular 2 application" really aren't sufficient. Nothing in the stack trace you shared points to the js core.

Are you changing the odata verbosity? What other code is happening around the delete call? etc.

**Comment by garrytrinder** [comment]
The below setup is used in my scenario.

```
setup({
      baseUrl: this.webUrl,
      headers: {
        'Authorization': 'Bearer ' + sessionStorage.getItem('access_token')
      }
    });
```
No other code is running after the delete call.

I think this is an issue with the core.es5.js library in Angular and PnP Core. In all requests I've used so far, (GET,UPDATE,ADD) all have given a response payload when successful, but from what I can gather the DELETE does not return a response, but the core.es5.js library expects one so throws an error.

https://stackoverflow.com/questions/35734411/angular-2-web-api-json-parsing-error-syntax-error-unexpected-end-of-input#35734684

**Comment by patrick-rodgers** [comment]
From what you said this appears to be something with Angular 2's way of doing things? I don't see this as an error with sp-pnp-js as the delete call works in node and the browser. We are [handling the empty](https://github.com/SharePoint/PnP-JS-Core/blob/master/src/sharepoint/odata.ts#L32) response and returning an empty object - which is the behavior I see in my testing. Unsure what resolution you are looking for on this as this seems to be a problem with something in Angular2?

**Comment by patrick-rodgers** [comment]
@garrytrinder - any update on this? Want to help but not sure there is anything we can do on this end.

**Comment by garrytrinder** [comment]
@patrick-rodgers apologies for the delay on this, I've been on annual leave and just come back so not been able to look into this for a few weeks. I'll do some more digging around and come back to you.

**Comment by patrick-rodgers** [comment]
Going to close this one for now due to inactivity - please _reopen_ if you need further assistance. In this case I am also not sure the issue lies with this library. Thanks!

**Comment by garrytrinder** [comment]
@patrick-rodgers I've done some more digging on this and might have found something...

You mentioned that you return an empty object however what I'm seeing is that when the request is fired, a 200 is being returned instead, so missing the line of code you highlighted.

The below shows the request in the Network tab and the line of code being hit, the fact that the item is deleted, to me, shows that the request is being successful but the expected response is wrong...

![image](https://user-images.githubusercontent.com/11563347/27885331-8950661e-61cf-11e7-98e4-5ae04e46231d.png)

**Comment by patrick-rodgers** [comment]
In that line (38 in your image) it is a 200 response OR content length of 0 - so I think that line should still run unless there is no Content-Length header coming back. I just checked and I am definitely getting back Content-Length in SPO when I do a delete and going down the expected code path. Is something in your application stripping the headers (I wouldn't think so)? If you put a break point on the if and check does the Content-Length header exist and have a value? There are also two requests when you do a delete - one to get the digest and one to do the delete - is this the digest call?

**Comment by garrytrinder** [comment]
I wouldn't suspect that it would strip anything out. As far as I know the error is being picked up by zone.js which Angular uses for change detection of promises and observables, so this shouldn't cause an issue.

**Comment by garrytrinder** [comment]
I've raised this issue in the angular gitter channel and it would appear that the error is being bubbling up & being caught by zone.js
There are some diagnostic checks I can run in Angular to investigate this further, but early indications are that it's being caused by a JSON parse within PnP Core.

**Comment by garrytrinder** [comment]
For those using Angular 2 and looking into issues with HTTP calls, add the following line to your polyfills.ts to get the full stack trace to track down where issues are bubbling up from :)

`import 'zone.js/dist/long-stack-trace-zone.min'; `

@patrick-rodgers here is the full stack trace, the error is originating from odata.js

```
Error: Uncaught (in promise): SyntaxError: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at odata.js:42
    at new ZoneAwarePromise (zone.js:833)
    at ODataDefaultParser.ODataParserBase.parse (odata.js:36)
    at odata.js:352
    at ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.es5.js:4149)
    at ZoneDelegate.invoke (zone.js:390)
    at Zone.run (zone.js:141)
    at zone.js:817
    at ZoneDelegate.invokeTask (zone.js:424)
    at odata.js:42
    at new ZoneAwarePromise (zone.js:833)
    at ODataDefaultParser.ODataParserBase.parse (odata.js:36)
    at odata.js:352
    at ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.es5.js:4149)
    at ZoneDelegate.invoke (zone.js:390)
    at Zone.run (zone.js:141)
    at zone.js:817
    at ZoneDelegate.invokeTask (zone.js:424)
    at resolvePromise (zone.js:769)
    at zone.js:695
    at zone.js:711
    at ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.es5.js:4149)
    at ZoneDelegate.invoke (zone.js:390)
    at Zone.run (zone.js:141)
    at zone.js:817
    at ZoneDelegate.invokeTask (zone.js:424)
    at Object.onInvokeTask (core.es5.js:4140)
    at ____________________Elapsed_70118_ms__At__Sat_Jul_15_2017_10_15_21_GMT_0100__GMT_Summer_Time_ ()
    at Object.onScheduleTask (long-stack-trace-zone.min.js:1)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Object.onScheduleTask (zone.js:300)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Zone.scheduleTask (zone.js:235)
    at Zone.scheduleMicroTask (zone.js:255)
    at scheduleResolveOrReject (zone.js:815)
    at resolvePromise (zone.js:764)
    at ____________________Elapsed_1_ms__At__Sat_Jul_15_2017_10_15_21_GMT_0100__GMT_Summer_Time_ ()
    at Object.onScheduleTask (long-stack-trace-zone.min.js:1)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Object.onScheduleTask (zone.js:300)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Zone.scheduleTask (zone.js:235)
    at Zone.scheduleMicroTask (zone.js:255)
    at scheduleResolveOrReject (zone.js:815)
    at resolvePromise (zone.js:764)
    at ____________________Elapsed_0_ms__At__Sat_Jul_15_2017_10_15_21_GMT_0100__GMT_Summer_Time_ ()
    at Object.onScheduleTask (long-stack-trace-zone.min.js:1)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Object.onScheduleTask (zone.js:300)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Zone.scheduleTask (zone.js:235)
    at Zone.scheduleMicroTask (zone.js:255)
    at scheduleResolveOrReject (zone.js:815)
    at resolvePromise (zone.js:764)
    at ____________________Elapsed_1_ms__At__Sat_Jul_15_2017_10_15_21_GMT_0100__GMT_Summer_Time_ ()
    at Object.onScheduleTask (long-stack-trace-zone.min.js:1)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Object.onScheduleTask (zone.js:300)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Zone.scheduleTask (zone.js:235)
    at Zone.scheduleMicroTask (zone.js:255)
    at scheduleResolveOrReject (zone.js:815)
    at resolvePromise (zone.js:764)
    at ____________________Elapsed_0_ms__At__Sat_Jul_15_2017_10_15_21_GMT_0100__GMT_Summer_Time_ ()
    at Object.onScheduleTask (long-stack-trace-zone.min.js:1)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Object.onScheduleTask (zone.js:300)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Zone.scheduleTask (zone.js:235)
    at Zone.scheduleMicroTask (zone.js:255)
    at scheduleResolveOrReject (zone.js:815)
    at resolvePromise (zone.js:764)
    at ____________________Elapsed_0_ms__At__Sat_Jul_15_2017_10_15_21_GMT_0100__GMT_Summer_Time_ ()
    at Object.onScheduleTask (long-stack-trace-zone.min.js:1)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Object.onScheduleTask (zone.js:300)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Zone.scheduleTask (zone.js:235)
    at Zone.scheduleMicroTask (zone.js:255)
    at scheduleResolveOrReject (zone.js:815)
    at resolvePromise (zone.js:764)
    at ____________________Elapsed_1_ms__At__Sat_Jul_15_2017_10_15_21_GMT_0100__GMT_Summer_Time_ ()
    at Object.onScheduleTask (long-stack-trace-zone.min.js:1)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Object.onScheduleTask (zone.js:300)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Zone.scheduleTask (zone.js:235)
    at Zone.scheduleMicroTask (zone.js:255)
    at scheduleResolveOrReject (zone.js:815)
    at resolvePromise (zone.js:764)
    at ____________________Elapsed_4_ms__At__Sat_Jul_15_2017_10_15_21_GMT_0100__GMT_Summer_Time_ ()
    at Object.onScheduleTask (long-stack-trace-zone.min.js:1)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Object.onScheduleTask (zone.js:300)
    at ZoneDelegate.scheduleTask (zone.js:404)
    at Zone.scheduleTask (zone.js:235)
    at Zone.scheduleMicroTask (zone.js:255)
    at scheduleResolveOrReject (zone.js:815)
    at resolvePromise (zone.js:764)
```

**Comment by garrytrinder** [comment]
I still think this is down to the wrong status code being returned. 200 is being returned but without a body, so when res.json() is called it throws an exception, 204 is handled in the code but I'm not seeing a scenario where that code would execute.

**Comment by garrytrinder** [comment]
@patrick-rodgers sorry to chase you on this, I know that you are very busy, just wondered if you had any thoughts on my findings.

**Comment by patrick-rodgers** [comment]
I am currently on family leave - but I still can't reproduce this. I.e. when I test this I always end up in the "then" block as expected for deletes. If the only repro is "create an angular app" I have to lean towards the issue residing there. If you can put together a PR that resolves this I am happy to have a look - but unsure what action should be taken. A 200 with no body is valid, but I do not encounter a situation not covered by the content length check. It isn't that I don't want to fix this, but I don't want to blindly fix something I can't reproduce.

**Comment by garrytrinder** [comment]
@patrick-rodgers appreciate the reply, even more so that you are on leave. 

I was just trying to get some movement on what could be causing the issue, appreciate that this is a difficult one and by no means am I saying that **you** should be fixing this :) 

Hope you are having some good time off, I'll feedback when I've done some more digging 👍

**Comment by garrytrinder** [comment]
Easy workaround for this is to use Recycle method instead of Delete, no error is thrown and works as expected, closing issue.

**Comment by simkessy** [comment]
@patrick-rodgers  I get this issue as well coming from odata.js: 


```
odata.js:41 Uncaught (in promise) SyntaxError: Unexpected end of input
    at odata.js:41
    at Promise (<anonymous>)
    at t.e.parse (odata.js:35)
    at odata.js:354
    at <anonymous>
(anonymous) @ odata.js:41
e.parse @ odata.js:35
(anonymous) @ odata.js:354
```
It happens when I delete lists and update fields:

```
// ------------- Delete Lists -------------//
deleteLists = function () {
    var b = $pnp.sp.createBatch();
    $pnp.sp.web.lists.getByTitle("Meeting Minutes").inBatch(b).delete();
    $pnp.sp.web.lists.getByTitle("Decisions").inBatch(b).delete();
    $pnp.sp.web.lists.getByTitle("Decision Tasks").inBatch(b).delete();
    $pnp.sp.web.lists.getByTitle("Template Tasks").inBatch(b).delete();
    $pnp.sp.web.lists.getByTitle("Project Task List").inBatch(b).delete();

    return b.execute();
};

project.update = {
    field: null,
    batch: null,
    list: null,
    set: function (listName) {
        nrg.update.batch = $pnp.sp.createBatch();
        nrg.update.list = $pnp.sp.web.lists.getByTitle(listName);
        nrg.update.field = nrg.update.list.fields;
    },
    fieldName: function (internal, display) {
        console.log("update:", internal, display);
        nrg.update.field.getByInternalNameOrTitle(internal).inBatch(nrg.update.batch).update({
            Title: display
        });
    },
    meetingMinutes: function () {
        nrg.update.set('Meeting Minutes');

        // Renames 
        nrg.update.fieldName("Title", "Topic");
        nrg.update.fieldName("Notes", "Agenda/Notes");

        return nrg.update.batch.execute();
    },
}
```

The operations work fine however.

**Comment by patrick-rodgers** [comment]
Reopening this. I've finally been able to duplicate it. So unsure if this was a change that rolled out to the farms and I got it later or what. This is related to #545. Basically 200 responses should per the spec always have a body, even if that body is {}. Now these seem to be coming back with nothing. I am working on a fix that will take care of both issues as well and any other similar 200 empty body cases we might have missed. Thanks!

**Comment by patrick-rodgers** [comment]
Closing as fixed in #559

**Comment by zuhairrizvi** [comment]
@patrick-rodgers  @garrytrinder @simkessy  Although I have switched to version 2.0.8 but I'm still having issues with it. I'm trying to batch delete list items.

var batch = sp.sp.createBatch();
 sp.sp.web.lists.getByTitle(this.ListName).items.getById(this.formId).attachmentFiles.getByName(this.DeletedFiles[i]["name"]).inBatch(batch).delete().then(v => {

});
